### ISSUE TITLE
How to trigger Sign in/Sign up modal programmaticaly ? 

### ISSUE THREAD

**Issue by suchcodemuchwow** [clerkinc/javascript#1399] opened 2023-06-22 01:28 UTC
I have a webpage where users are able to look at the public pages but cannot interact with (like/comment etc.). I would like to show them the Sign in or Sign up modal when they try to do these actions. I can redirect them to sign in or sign up page but that's not what I am trying to achieve from UX perspective.

- [x] Review the documentation: https://clerk.com/docs
- [x] Go through package changelog files.

**Comment by nikosdouvlis** [comment] 2023-06-22 08:50
Hello @suchcodemuchwow,
you could probably use the `openSignIn` and `openSignUp` helpers: 

```
window.Clerk.openSignIn()
```

or

```
const clerk = useClerk();
clerk.openSignIn()
```

Closing this one as this is not a bug report per se, feel free to use our [discord server for support requests](https://discord.com/invite/b5rXHjAg7A) :)

**Closed by nikosdouvlis** 2023-06-22 08:50 UTC

**Comment by clerk-cookie** [comment] 2024-06-22 00:01
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
