### ISSUE TITLE
Clerk Chrome Extension not working. Manifest V3 

### ISSUE THREAD

**Issue by Vaqxin** [clerkinc/javascript#1401] opened 2023-06-22 02:11 UTC
## Package + Version

- [ x] `@clerk/chrome-extension`

### Dependencies + versions

```

`{
  "name": "wizevine",
  "version": "0.0.0",
  "author": "no one",
  "description": "",
  "type": "module",
  "license": "MIT",
  "keywords": [
    "chrome-extension",
    "react",
    "vite",
    "create-chrome-ext"
  ],
  "engines": {
    "node": ">=14.18.0"
  },
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "fmt": "prettier --write '**/*.{jsx,js,json,css,scss,md}'"
  },
  "dependencies": {
    "@clerk/chrome-extension": "^0.3.14",
    "@headlessui/react": "^1.7.13",
    "@heroicons/react": "^2.0.16",
    "dotenv": "^16.3.1",
    "flowbite": "^1.6.5",
    "flowbite-react": "^0.4.3",
    "openai": "^3.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@crxjs/vite-plugin": "^1.0.12",
    "@types/react": "^18.0.14",
    "@types/react-dom": "^18.0.5",
    "@vitejs/plugin-react": "^1.3.2",
    "autoprefixer": "^10.4.14",
    "postcss": "^8.4.21",
    "prettier": "^2.7.1",
    "tailwindcss": "^3.2.7",
    "vite": "^2.9.13"
  }
}
`



## Description

CSP is blocking  clerk chrome extension from loading vital scripts. 

`@clerk_chrome-extension.js?v=1d0ce8ee:18680 Refused to load the script 'https://good-bunny-39.clerk.accounts.dev/npm/@clerk/clerk-js@4/dist/clerk.browser.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

**Comment by dimkl** [comment] 2023-06-22 08:55
@Vaqxin thank you for reporting this issue.
Have you tried this template repo ? https://github.com/clerkinc/clerk-chrome-extension-starter/
Could you also provide the `manifest.json` you are using?

**Comment by azamuddin** [comment] 2023-06-25 23:29
Is this the same cause? https://github.com/clerkinc/javascript/issues/1412#issuecomment-1606101488

**Comment by SokratisVidros** [comment] 2023-06-27 09:42
@Vaqxin <ClerkProvider/> is trying to hot-load ClerkJS on runtime. This is supposed to happen only when Clerk is used in a web app and not in an extension.

Please ensure you are using the latest version of @clerk/chrome-extension package and try again.

**Comment by Vaqxin** [comment] 2023-07-03 19:10
@SokratisVidros Im following the docs. Not doing anything different. 

  "@clerk/chrome-extension": "^0.3.19",

Still getting the error even after updating vite - 

`@clerk_chrome-extension.js?v=a0e5625d:18700 Refused to load the script 'https://good-bunny-39.clerk.accounts.dev/npm/@clerk/clerk-js@4/dist/clerk.browser.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

(anonymous) @ @clerk_chrome-extension.js?v=a0e5625d:18700
2Popup.jsx:59 PASSED TAG TEST
@clerk_chrome-extension.js?v=a0e5625d:19719 Uncaught (in promise) Error: Clerk: Failed to load Clerk
    at @clerk_chrome-extension.js?v=a0e5625d:19719:11
    at async _IsomorphicClerk.loadClerkJS (@clerk_chrome-extension.js?v=a0e5625d:20286:11)`

**Comment by Vaqxin** [comment] 2023-07-07 05:56
@SokratisVidros this seems to be an issue with Vite and @clerk/chrome-extension

**Comment by colinclerk** [comment] 2023-07-11 22:24
Hello - can you provide a minimal reproduction for us?

That load is generally triggered by `<ClerkProvider>` in web apps, but the `<ClerkProvider>` inside `@clerk/chrome-extension` is designed to skip it.  At first glance, it's not obvious why Vite would trigger this load but not CRA (as in the starter)

**Comment by Vaqxin** [comment] 2023-07-13 02:24
Easiest would be using - https://github.com/guocaoyi/create-chrome-ext - React, Javascript - installing Clerk and importing into popup.jsx

**Comment by Vaqxin** [comment] 2023-07-13 03:58
Have you guys tested this in anything other than CRA? I just made a fresh project with webpack5 not vite and Im getting the exact same error @colinclerk @dimkl Thanks!

<img width="1148" alt="Screenshot 2023-07-12 at 11 57 58 PM" src="https://github.com/clerkinc/javascript/assets/7260220/3fbbdfdf-3195-4fbf-b985-c738132ac3ed">

**Comment by devagrawal09** [comment] 2023-07-13 23:47
Hi @Vaqxin,
Thank you for reporting the issue. We have narrowed the bug to `@clerk/clerk-js` v4.45 which is a dependency of `@clerk/chrome-extension` v0.3.7 onwards.
For now you can lock the versions of both these libraries in your package.json and it should work.
```json
    "@clerk/chrome-extension": "0.3.6",
    "@clerk/clerk-js": "4.44.0",
```
Once this is fixed in the latest version of clerk-js I will let you know and you should be able to upgrade to the latest version of the library then.

**Comment by Vaqxin** [comment] 2023-07-14 02:30
@devagrawal09  Thanks for the reply! - Updated my deps to the versions mentioned, unfortunately using those packages still results in the same issues.  Looking to launch my AI app in a week and this has been a roadblock for me. Really like what Clerk is building that's why I'm willing to delay. Hopefully a patch on the next release will help. 
<img width="1148" alt="Screenshot 2023-07-13 at 10 28 14 PM" src="https://github.com/clerkinc/javascript/assets/7260220/22ef9b3d-7523-4965-829c-281b098510e0">
<img width="243" alt="Screenshot 2023-07-13 at 10 30 50 PM" src="https://github.com/clerkinc/javascript/assets/7260220/2ba6a3c6-544c-4ebd-96e1-e6c1cc485699">

**Comment by nikosdouvlis** [comment] 2023-07-14 09:42
Hello @Vaqxin, I'm looking into this as well but I'm having trouble reproducing the issue after pinning the versions as Dev instructed. 
Could you please share the output of running `npm ls -a | grep -e '@clerk'`? Sharing your package-lock file would also be helpful.

**Comment by Vaqxin** [comment] 2023-07-14 14:57
@nikosdouvlis Looking forward to your updates!

**Comment by nikosdouvlis** [comment] 2023-07-16 14:55
Hello @Vaqxin :) 
Could you try using the following version? You don't need to have `clerk/clerk-js` listed as a direct dependency anymore, so please remove that and install:
```
npm i @clerk/chrome-extension@0.3.22-snapshot.6f39cb6
```
Let me know if this works for you - we'll be running more tests and push out the fix in a stable release this week.

**Comment by Vaqxin** [comment] 2023-07-17 16:44
@nikosdouvlis It is indeed now working! Thanks!

**Closed** 2023-07-19 08:38 UTC
Labels: chrome-extension

**Comment by kaminskypavel** [comment] 2023-12-19 22:39
Unfortunately not working for me.

```
    "@clerk/chrome-extension": "^0.6.0",
    "@clerk/clerk-react": "^4.30.0",
```

```js
@clerk_clerk-react.js?v=eb21b892:354 Refused to load the script 'https://sacred-sheep-79.clerk.accounts.dev/npm/@clerk/clerk-js@4/dist/clerk.browser.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

@nikosdouvlis can you please reopen?

**Comment by tmilewski** [comment] 2023-12-20 14:24
Hey @kaminskypavel & @jellohouse!

Would you mind confirming the following for me?

- That `ClerkProvider` is being imported from `@clerk/chrome-extension` and not `@clerk/clerk-react`. The provider from `@clerk/chrome-extension` operates differently to support that environment.
- That your `manifest.json` includes the domain refusing to load in `host_permissions`.

Thanks!

**Comment by kaminskypavel** [comment] 2023-12-20 17:29
> Hey @kaminskypavel & @jellohouse!
> 
> Would you mind confirming the following for me?
> 
> * That `ClerkProvider` is being imported from `@clerk/chrome-extension` and not `@clerk/clerk-react`. The provider from `@clerk/chrome-extension` operates differently to support that environment.
> * That your `manifest.json` includes the domain refusing to load in `host_permissions`.
> 
> Thanks!

you're correct! I missed the `host_permissions` in `manifest.json`, my bad, thanks for the hint.
It now loads, but never authenticates :/

![image](https://github.com/clerk/javascript/assets/4253088/289bfe44-63d2-4c8d-9479-b03a8c16be7d)

I can also confirm this with the `useAuth` hook

![image](https://github.com/clerk/javascript/assets/4253088/aead7cc8-bc21-4d64-bf76-a1152ff2c9e0)


_specs_
Browser : Brave [Version 1.61.104 Chromium: 120.0.6099.115 (Official Build) (64-bit)](https://brave.com/latest/)

what am I missing?

**Comment by donguyen94** [comment] 2024-10-23 12:19
I am deploying an extension with manifest v3 and I encountered the following error: 'content-script-loader.content.js-DvdIAllm-BikncYZc.js:7 Refused to load the script 'chrome-extension://1bd8059a-36e9-4894-aa6c-98abb7a88879/assets/content.js-DvdIAllm.js' because it violates the following Content Security Policy directive: 'script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost/:* http://127.0.0.1/:*'. Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.' Can anyone help me?
 Here is the code of my manifest file:
    {
      "name": "Social listening chrome extension",
      "version": "0.0.1",
      "description": "Social listening chrome extension",
      "manifest_version": 3,
      "content_security_policy": {
        "extension_pages": "script-src 'self' 'wasm-unsafe-eval'; object-src 'self';"
      },
      "action": {
        "default_popup": "index.html",
        "default_icon": {             
          "16": "src/assets/images/icon-16.png",
          "24": "src/assets/images/icon-24.png",
          "32": "src/assets/images/icon-32.png",
          "128": "src/assets/images/icon-128.png"
        }
      },
      "permissions": [
          "storage",
          "unlimitedStorage",
          "webRequest"
      ],
      "host_permissions": [
        "*://*/*"
      ],
      "content_scripts": [
        {
          "matches": [
            "*://*.instagram.com/*"
          ],
          "js": [
            "content.js"
          ],
          "run_at": "document_start",
          "all_frames": true
        }
      ],
      "background": {
        "service_worker": "src/background/service-worker.js" 
      },
      "web_accessible_resources": [{
        "resources": ["injected.js"],
        "matches": ["<all_urls>"]
      }]
    }
    package.json:
    {
  "name": "social-listening-chrome-extension",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@crxjs/vite-plugin": "^1.0.14",
    "@types/chrome": "^0.0.268",
    "axios": "^1.7.2",
    "file-type": "^19.6.0",
    "is-url": "^1.2.4",
    "isomorphic-fetch": "^3.0.0",
    "jpeg-js": "^0.4.4",
    "level-js": "^6.1.0",
    "node-fetch": "^3.3.2",
    "object-assign": "^4.1.1",
    "png.js": "^0.2.1",
    "tesseract.js": "^5.1.1",
    "tesseract.js-core": "^5.1.1",
    "typedarray-to-buffer": "^4.0.0",
    "vue": "^3.4.21",
    "vue-router": "^4.3.3",
    "xlsx": "^0.18.5"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.10.2",
    "autoprefixer": "^10.4.19",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.3",
    "typescript": "^5.2.2",
    "vite": "^2.9.18",
    "vue-tsc": "^2.0.6"
  }
}

**Comment by clerk-cookie** [comment] 2025-10-24 00:01
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
