### ISSUE TITLE
[SDK-810] React Expo: A white screen appears right after splash.

### ISSUE THREAD

**Issue by j3rech0** [clerkinc/javascript#1713] opened 2023-09-12 15:45 UTC
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerkinc/javascript/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction / Replay Link

https://github.com/j3rech0/clerk-expo

### Publishable key

pk_test_Z3Jvd24tc25pcGUtOTMuY2xlcmsuYWNjb3VudHMuZGV2JA

### Description

Cloned from [https://github.com/clerkinc/clerk-expo-starter](https://github.com/clerkinc/clerk-expo-starter).
- no code changes
- `npm install`
- `npm start`
- Run using Expo Go on an actual device

Statusbar also disappears

https://github.com/clerkinc/javascript/assets/113246741/7f5c9527-10a8-4da2-83e1-bff69c769434

I change the initial screen background to black here

https://github.com/clerkinc/javascript/assets/113246741/68390202-e3e9-4d35-804a-2e215d5b6a49

**Expected behavior:**
It should load the initial screen after the splash in `app.json`

I have to add ```<ClerkLoading />``` at [https://github.com/j3rech0/clerk-expo/blob/main/navigation/index.tsx#L39](https://github.com/j3rech0/clerk-expo/blob/main/navigation/index.tsx#L39). to compensate to that noticeable gap and It's the only easy fix I found so far, and used it on my published app.

### Environment

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 18.82 GB / 31.78 GB
  Binaries:
    Node: 20.3.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.29.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.22621.2215.0), Chromium (116.0.1938.76)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @babel/core: ^7.22.8 => 7.22.8
    @clerk/clerk-expo: ^0.18.12 => 0.18.12
    @expo/vector-icons: 13.0.0 => 13.0.0
    @react-navigation/bottom-tabs: 6.5.8 => 6.5.8
    @react-navigation/native: 6.1.7 => 6.1.7
    @react-navigation/native-stack: 6.9.13 => 6.9.13
    @types/expo: 33.0.1 => 33.0.1
    @types/react: ^18.2.14 => 18.2.14
    @types/react-native: ^0.72.2 => 0.72.2
    expo: ~49.0.0 => 49.0.0
    expo-asset: 8.10.1 => 8.10.1
    expo-auth-session: 5.0.2 => 5.0.2
    expo-constants: 14.4.2 => 14.4.2
    expo-font: 11.4.0 => 11.4.0
    expo-linking: 5.0.2 => 5.0.2
    expo-random: 13.2.0 => 13.2.0
    expo-secure-store: 12.3.1 => 12.3.1
    expo-splash-screen: 0.20.4 => 0.20.4
    expo-status-bar: 1.6.0 => 1.6.0
    expo-web-browser: 12.3.2 => 12.3.2
    jest-expo: ^49.0.0 => 49.0.0
    prettier: ^2.8.4 => 2.8.8
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    react-native: 0.72.1 => 0.72.1
    react-native-safe-area-context: 4.6.3 => 4.6.3
    react-native-screens: 3.22.1 => 3.22.1
    react-native-url-polyfill: 1.3.0 => 1.3.0
    react-native-web: 0.19.6 => 0.19.6
    typescript: ^5.1.6 => 5.1.6
    uri-scheme: 1.1.0 => 1.1.0
```

<sub>[SDK-810](https://linear.app/clerk/issue/SDK-810/react-expo-a-white-screen-appears-right-after-splash)</sub>

**Comment by anagstef** [comment] 2023-10-25 19:21
Hello, @j3rech0! 

The flickering issue arises because the splash screen is hidden before the Clerk has finished loading its state. To address this, you can consider the solution proposed [in this PR in our expo-starter repository](https://github.com/clerkinc/clerk-expo-starter/pull/15). 

However, it's important to note that how you handle this situation is ultimately a decision for you to make. One potential approach is to hide the splash screen early and display a loading screen until Clerk finishes loading. This can enhance the user experience and give the app a more responsive feel (which you have already done using the <ClerkLoading> component). 

Regarding the reported problem with the Status Bar disappearing, I haven't been able to reproduce it myself. This issue may be specific to some Android devices and unrelated to Clerk.

Closing this issue as it is not related to our core product. If you have more issues with our [clerk-expo-starter](https://github.com/clerkinc/clerk-expo-starter) repo, feel free to open a new issue there.

**Closed by anagstef** 2023-10-25 19:21 UTC
Labels: needs-triage, linear, Medium priority

**Comment by clerk-cookie** [comment] 2025-01-08 00:02
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
