### ISSUE TITLE
Sign up callback function

### ISSUE THREAD

**Issue by suchcodemuchwow** [clerkinc/javascript#1400] opened 2023-06-22 01:33 UTC
I would like to call some apis after users signup I couldn't find any option for that in docs and wondering if there is a callback function or some type of listener for the first time registration.

- [x] Review the documentation: https://clerk.com/docs
- [x] Go through package changelog files.

**Comment by dimkl** [comment] 2023-06-22 09:19
Hello @suchcodemuchwow 
It depends on whether you want to make those API calls from your server or from the browser

From the server you could use the `user.created` [webhook](https://clerk.com/docs/integration/webhooks).

From the browser you could you the `afterSignupUrl` prop (for custom flows) or the `After sign-up redirect` from the `Clerk Dashboard > Paths` to setup a route that will trigger those API calls based.

Closing this one as this is not a bug report per se, feel free to use our [discord server for support requests](https://discord.com/invite/b5rXHjAg7A) :)

**Closed by dimkl** 2023-06-22 09:19 UTC

**Comment by clerk-cookie** [comment] 2024-06-22 00:01
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
