### ISSUE TITLE
App breaks with 401 if v2_errorBoundary is set to true

### ISSUE THREAD

**Issue by ZeldOcarina** [clerkinc/javascript#1089] opened 2023-04-20 16:30 UTC
"dependencies": {
    "@aws-sdk/client-s3": "^3.306.0",
    "@clerk/remix": "^2.5.5",
    "@googlemaps/js-api-loader": "^1.15.1",
    "@popperjs/core": "^2.11.7",
    "@prisma/client": "^4.13.0",
    "@remix-run/node": "^1.15.0",
    "@remix-run/react": "^1.15.0",
    "@remix-run/vercel": "^1.15.0",
    "@types/yaireo__tagify": "^4.17.0",
    "@vercel/node": "^2.6.2",
    "@vercel/remix": "^1.15.0",
    "@yaireo/tagify": "^4.17.7",
    "aws-sdk": "^2.1348.0",
    "isbot": "^3.6.5",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.8.0",
    "react-phone-input-2": "^2.15.1",
    "react-popper": "^2.3.0",
    "react-spinners": "^0.13.8",
    "slugify": "^1.6.6"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.15.0",
    "@remix-run/eslint-config": "^1.15.0",
    "@remix-run/serve": "^1.15.0",
    "@types/react": "^18.0.25",
    "@types/react-dom": "^18.0.8",
    "eslint": "^8.27.0",
    "prettier": "2.8.7",
    "prisma": "^4.13.0",
    "tailwindcss": "^3.3.1",
    "typescript": "^4.8.4"
  },

### Dependencies + versions

Provide a json with the dependencies used in your project (copy paste from yarn.lock / package-lock.json) or a github project / template that reproduces the issue.

**Include the @clerk/* packages and their versions!**

Example:

### Browser/OS

`Chrome latest`

## Description

Describe your issue in detail, a demo repository or a sandbox would be great.

I've been trying to debug Remix just giving me a 401 after carefully following the QuickStart then realized there's no more CatchBoundary in v2 if you add v2_errorBoundary: true as described [here](https://remix.run/docs/en/main/pages/v2#catchboundary-and-errorboundary):

Not sure how to solve it. I've removed the flag for now but I think the repo should be future-proofed as now I need to change all the error handlings in the app as I was using the v2 version everywhere.

I'll see if I make it to add on v2 Clerk and let you know here if I'll make it.

Thank you!

**Comment by dimkl** [comment] 2023-04-20 16:40
Hello @ZeldOcarina thank you for reporting this.
I will close it as duplicate of https://github.com/clerkinc/javascript/issues/965.
Subscribe to the issue for any changes.

PS: please try to follow the Issue template and check for existing issues before submitting new issues.

**Closed by dimkl** 2023-04-20 16:40 UTC
Labels: duplicate

**Comment by ZeldOcarina** [comment] 2023-04-20 18:33
Sorry I did not sure why I couldn't find it!
