### ISSUE TITLE
A white screen appear right after splash. 

### ISSUE THREAD

**Issue by j3rech0** [clerkinc/javascript#1707] opened 2023-09-12 09:27 UTC
I've been trying to figure out the cause of this issue when I tried to build using this repo template, it seems that whenever ```<ClerkLoaded />``` is rendered a white screen appears just before splash is finished, I've tried most of the solutions found on the internet but I ended up adding ```<ClerkLoading />``` above `ClerkLoaded` and that seems to fixed on my end.

Similar to this one : https://www.reddit.com/r/reactnative/comments/111x6qc/after_the_app_launch_i_am_seeing_this_blank/

**Comment by dimkl** [comment] 2023-09-12 13:06
hello @j3rech0 👋 
Could you please use the bug report template and provide the requested information in order to help us investigate your issue?

**Comment by j3rech0** [comment] 2023-09-12 13:40
@dimkl I'll do later, I just grabbed a fresh copy from [https://github.com/clerkinc/clerk-expo-starter](https://github.com/clerkinc/clerk-expo-starter) then run it on my advice using Expo Go, no actual code changes just cloned and run. White screen is noticeable for 1-2seconds.

**Comment by dimkl** [comment] 2023-09-12 16:29
Duplicate of https://github.com/clerkinc/javascript/issues/1713

**Closed by dimkl** 2023-09-12 16:29 UTC

**Comment by clerk-cookie** [comment] 2024-09-12 00:01
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
