### ISSUE TITLE
Adapt Remix package to run on Cloudflare Workers

### ISSUE THREAD

**Issue by MedicusIO** [clerkinc/javascript#127] opened 2022-03-20 06:48 UTC
## Package

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [X] `@clerk/remix`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend-core`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/edge`
- [ ] other:

## Description
The rootAuthLoader uses http2 which is a node package. Cloudflare Workers does not have access to Node.js packages, just plain javascript. Can this not be changed to fetch?

**Comment by nikosdouvlis** [comment] 2022-03-24 00:06
Thanks for reporting that. A ticket for this issue already exists, so let me get back at you once the fix is deployed - will probably happen soon enough :)

**Comment by igneel64** [comment] 2022-03-24 10:05
Hey @MedicusIO :) 
Can you please gives us some information on your setup and the packages used ? _(an example repo would be even better)_

**Comment by MedicusIO** [comment] 2022-03-24 17:44
After much soul searching I switched to Fly.IO which runs node (so this is less of an issue to me now). Cloudflare workers run V8 so anything that runs in the browser runs in a worker. The upside is there is no cold start like with lambda. However, you cannot use any node packages which is limiting.

**Comment by Slooowpoke** [comment] 2022-04-20 20:17
I've encountered this too I think, even just trying to run mini flare with Clerk doesn't seem to work.

I'm guessing it's because of Clerk only because of this error:
```
../../node_modules/http2-wrapper/source/index.js:2:22:
      2 │ const http2 = require('http2');
        ╵                       ~~~~~~~
  The package "http2" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```

If I search through all the packages in the project for the ones that use http-wrapper, the only one I get is one called "got", which is used in Clerk-node. I'll try and put together a simple reproduction case but it might take until this weekend.

**Comment by igneel64** [comment] 2022-04-21 07:13
Thanks peeps, it would be really helpful for us to start checking the issue based on the setup and give you a resolution.

**Comment by Slooowpoke** [comment] 2022-04-21 07:55
Found five minutes this morning and it was actually easier than I thought to reproduce.
https://github.com/Slooowpoke/clerk-remix-workers

This is a fresh remix repo with Cloudflare workers set as the deployment target, I've added Clerk and the root auth loader, nothing else. If you try to run this, it won't work. If you remove clerk from root.tsx it works. Hope that's helpful.

**Comment by SokratisVidros** [comment] 2022-05-09 09:44
`clerk-remix` depends on `clerk-node-sdk` that uses [got HTTP client](https://www.npmjs.com/package/got). That is, the current version of `clerk-remix` works for Node runtimes. I will a PR later today with [cross-fetch](https://www.npmjs.com/package/cross-fetch) to see if it resolves the issue.

**Comment by EArazli** [comment] 2022-05-13 09:05
Thanks for the update! Not sure if this helps, but CF workers implements the [web crypto api](https://developers.cloudflare.com/workers/runtime-apis/web-crypto/) and there seems to be something similar to cross-fetch for that use case. https://www.npmjs.com/package/isomorphic-webcrypto

There also seems to be support for the web crypto API in node directly but the earliest LTS with support seems to be 16
https://nodejs.org/api/webcrypto.html#web-crypto-api

**Comment by marcus-sa** [comment] 2022-06-13 10:03
+1 this is also blocking me. Anything we can do to help speed up the process?

**Comment by marcus-sa** [comment] 2022-06-13 10:06
> Thanks for the update! Not sure if this helps, but CF workers implements the [web crypto api](https://developers.cloudflare.com/workers/runtime-apis/web-crypto/) and there seems to be something similar to cross-fetch for that use case. https://www.npmjs.com/package/isomorphic-webcrypto
> 
> There also seems to be support for the web crypto API in node directly but the earliest LTS with support seems to be 16 https://nodejs.org/api/webcrypto.html#web-crypto-api

According to MDN, it's supported from v15.

**Comment by SokratisVidros** [comment] 2022-06-17 12:59
Folks, this is the first PR towards a more isomorphic architecture https://github.com/clerkinc/javascript/pull/290. It's still WIP but the direction should be very clear.

**Comment by marcus-sa** [comment] 2022-07-11 19:48
> Still working on it. The latest status is that we need to find an isomorphic HTTP clients and an isomorphic crypto library. The HTTP client we picked for now is [cross-fetch](https://github.com/lquixada/cross-fetch). Things are a bit trickier in the crypto world.

There's https://github.com/sindresorhus/ky-universal by the same people who created got.

**Comment by SokratisVidros** [comment] 2022-07-13 20:44
Hey @marcus-sa, the PR introducing fetch will be merged later this week. The next step is to bump to Node 16 and use webcrypto. Apologies this is taking longer than expected but more pressuring tasks came up as we are in the process of releasing ClerkJS V4 with brand new components.

**Comment by SokratisVidros** [comment] 2022-07-15 16:12
The first PR about fetch is now merged. Next week we will replace Node crypto with Web crypto.

**Comment by SokratisVidros** [comment] 2022-09-07 06:34
Apologies for the delay. We are currently working to support Next.js 12.2 middlewares. Cloudflare workers for Remix and other frameworks are next on the list.

**Comment by SokratisVidros** [comment] 2022-10-25 11:24
We expect this to be resolved in November. As you can see in https://github.com/clerkinc/javascript/pull/460/files we've started rearchitecting our backend SDKS to make them work across web-interoperable runtimes.

**Comment by arjunyel** [comment] 2023-03-21 00:40
I am currently using Clerk plus Cloudflare Pages so I believe this can be closed

**Comment by SokratisVidros** [comment] 2023-03-21 08:36
Yes, Remix is fully supported across all runtimes.

**Closed by SokratisVidros** 2023-03-21 08:36 UTC
Labels: remix-issue

**Comment by dimkl** [comment] 2023-03-21 11:07
@aerojeyenth  your issue is not related to this. i will reopen the previous issue.
